alias -g devel="~/Development"
alias dev="devel"
alias s="subl ."
alias zshrc="subl ~/.zshrc"
alias l="ls -gh"
alias dotfiles="cd $DOTFILES"
alias work="tmux -CC attach -t work"
alias resource="source ~/.zshrc"
